#!/home/ryo1/anaconda3/bin/python3
# SPDX-FileCopyrightText: 2025 Ryoichi Sakamaki
# SPDX-License-Identifier: BSD-3-Clause

import sys

print("fork")
x = 0.0
for n in sys.argv[1:]:
    x += float(n)
print(x)
